name: Measure coverage

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Query coverage information
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'temurin'
      - run: mvn -f pom.xml clean test
      - run: mvn jacoco:report

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: target/site/jacoco/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 80
          title: Code Coverage

      - name: Fail PR if overall coverage is less than 60%
        if: ${{ steps.jacoco.outputs.coverage-overall < 60.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')